version: '3.8'

services:
  # PostgreSQL 資料庫
  db:
    image: postgres:15-alpine
    container_name: vocab-db
    environment:
      - POSTGRES_USER=vocab_user
      - POSTGRES_PASSWORD=vocab_password
      - POSTGRES_DB=vocab_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vocab_user -d vocab_db"]
      interval: 30s
      timeout: 10s
      retries: 3

  # 後端 API 服務 (使用 PostgreSQL)
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: vocab-api-postgres
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+psycopg://vocab_user:vocab_password@db:5432/vocab_db
      - JWT_SECRET=your-super-secret-jwt-key-change-in-production
      - JWT_EXPIRE_HOURS=12
      - CORS_ORIGINS=http://localhost:3000,http://localhost:5173
      - RATE_LIMIT_PER_MIN=120
      - RATE_LIMIT_BURST=200
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # 前端 Web 服務
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: vocab-web-postgres
    ports:
      - "3000:80"
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
    depends_on:
      - api
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:

networks:
  default:
    name: vocab-network-postgres

