services:
  - type: web
    name: vocab-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRE_HOURS
        value: 12
      - key: CORS_ORIGINS
        sync: false
      - key: RATE_LIMIT_PER_MIN
        value: 120
      - key: RATE_LIMIT_BURST
        value: 200
      - key: DEBUG
        value: false

